#!/bin/bash

if [[ "$#" == "1" ]]; then
    FOLDERS=$1
else
    FOLDERS="*"
fi

for machine in working/${FOLDERS}; do
    for j in $(ls ${machine}); do 
    	echo ${machine##*/}/$j `ls ${machine}/$j | wc -l` `ls jobs/$j/log | wc -l`; 
    done
done
