#!/bin/bash

METAQ=/full/path/to/metaq
METAQ_X=${METAQ}/x
METAQ_LIB=${METAQ_X}/metaq_lib.sh
METAQ_VERBOSITY=3

if [[ ! -f ${METAQ_LIB} ]]; then
    echo "METAQ library is missing from ${METAQ_LIB}"
    exit
fi

source ${METAQ_LIB}

###
### CHECK JOBS AND RESET
###

for job in ${METAQ_WORKING_BASE}/*; do
    if [[ "$job" == "${METAQ_WORKING_BASE}/*" ]]; then
        echo "No jobs to consider."
        continue
    fi
    job_id=${job##*/}
    METAQ_PRINT 0 "Checking job ${job_id}..."
    if [[ -z "$(METAQ_JOB_RUNNING $job_id)" ]] ; then
        METAQ_PRINT 1 "Resetting jobs..."
        mv -v $job/* ${METAQ_PRIORITY} 2>/dev/null
        METAQ_PRINT 1 "Removing working directory..."
        rmdir $job
    else
        METAQ_PRINT 1 "Job is running."
    fi
done
