#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Exactly two arguments required:"
    echo "rm_old DIR DATE"
    echo "    DIR         a directory, possibly relative to the current directory"
    echo "    DATE        a date in ISO 8601 abbreviated format, YYYY-MM-DD."
    echo "Everything in DIR from before DATE will be deleted."
    exit
fi

dir=$1
date=$2

if [[ ! -d "${dir}" ]]; then
    echo "Target directory doesn't exist: ${dir}"
    exit
fi

if [[ ! "${date}" =~ [0123456789]{4}-[0123456789]{2}-[0123456789]{2} ]]; then
    echo "Date doesn't match YYYY-MM-DD formatting: '${date}'"
    exit
fi

count=$(find "$dir" ! -newermt $date -type f | wc -l)
echo "There are ${count} files that will be deleted."
if [[ "${count}" == "0" ]]; then
    echo "Nothing to do."
    exit
fi

read -p "DELETE all files in $dir older than $date ? y[es] / n[o]    " proceed
case $proceed in
    yes|Yes|y|Y) echo "  DELETING:"; find "$dir" ! -newermt $date -type f -print -delete ;;
    *) echo "    Exiting without deleting."; ;;
esac

