#!/bin/bash

if [[ ! "$#" == "1"  ]]; then
    echo "Mandatory argument: the machine name."
    exit
fi

METAQ_MACHINE=$1

METAQ=$( cd $(dirname $0)/.. ; pwd -P )
METAQ_X=${METAQ}/x
METAQ_LIB=${METAQ_X}/metaq_lib.sh
METAQ_VERBOSITY=3

if [[ ! -f ${METAQ_LIB} ]]; then
    echo "METAQ library is missing from ${METAQ_LIB}"
    exit
fi

source ${METAQ_LIB}


###
### CHECK JOBS AND RESET
###

if [[ "$(ls ${METAQ_WORKING_BASE}/${METAQ_MACHINE}/* 2>/dev/null | wc -l | tr -d '[:blank:]')" == "0" ]]; then
    echo "No jobs to consider."
    exit;
fi

for job in ${METAQ_WORKING_BASE}/${METAQ_MACHINE}/*; do
    if [[ "${job}" == "${METAQ_WORKING_BASE}/${METAQ_MACHINE}*" ]]; then
        echo "No jobs to consider."
        continue
    fi
    job_id=${job##*/}
    if [[ ! -z "$(METAQ_JOB_RUNNING $job_id)" ]] ; then
        METAQ_PRINT 0 "Job ${job_id}"
        for task in ${job}/*; do
            METAQ_PRINT 1 "${task}"
        done
    else
        METAQ_PRINT 0 "Job ${job_id} has been abandoned."
    fi
done
